services:
  # jellyfin:
  #   image: jellyfin/jellyfin:latest
  #   container_name: jellyfin
  #   restart: unless-stopped
  #   # network_mode: 'bridge'
  #   user: "501:20"
  #   volumes:
  #     # This directory will store Jellyfin config and metadata
  #     - ./config/jellyfin:/config
  #     - ./cache:/cache
  #     - type: bind
  #       source: /Volumes/ExtremeSSD/Movies
  #       target: /media/movies
  #     - type: bind
  #       source: /Volumes/ExtremeSSD/TV
  #       target: /media/tv
  #   environment:
  #     - TZ=America/New_York
  #     - JELLYFIN_PublishedServerUrl=https://88morgan.a5luan.org

  #   ports:
  #     - "8096:8096"
  #     - "8920:8920"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    command: tunnel run
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - WEBUI_PORT=8080
      - PUID=0
      - PGID=0
      - TZ=${TZ}
      # - DOCKER_MODS=ghcr.io/gabe565/linuxserver-mod-vuetorrent
    volumes:
      - ${COMMON_PATH_88}:/data
      - ./config/qbittorrent:/config
      - ${COMMON_PATH_88}/torrents:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
    volumes:
      - ./config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
    volumes:
      - ${COMMON_PATH_88}:/data
      - ./config/sonarr:/config
      - ${COMMON_PATH_88}/torrents:/downloads
      - ${COMMON_PATH_88}/media/tv:/tv
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
    volumes:
      - ${COMMON_PATH_88}:/data
      - ./config/radarr:/config
      - ${COMMON_PATH_88}/torrents:/downloads
      - ${COMMON_PATH_88}/media/movies:/movies
    ports:
      - 7878:7878
    restart: unless-stopped
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - 8191:8191
    restart: unless-stopped
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
    volumes:
      - ./config/sabnzbd/config:/config
      - ${COMMON_PATH_88}:/data
      # - ${COMMON_PATH_88}/usenet/downloads:/downloads
      # - ${COMMON_PATH_88}/usenet/incomplete:/incomplete-downloads
    ports:
      - 8081:8080
    restart: unless-stopped
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
    volumes:
      - ${COMMON_PATH_88}:/data
      - ${COMMON_PATH_88}/media/books:/books
      - ./config/readarr:/config
      - ${COMMON_PATH_88}/qbittorrent/downloads:/downloads
      # - ${COMMON_PATH_88}/usenet/downloads:/usenet-downloads
      # - ${COMMON_PATH_88}/usenet/incomplete:/usenet-incomplete-downloads
    ports:
      - 8787:8787
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
    volumes:
      - ./config/bazarr:/config
      - ${COMMON_PATH_88}:/data
      - ${COMMON_PATH_88}/media/movies:/movies
      - ${COMMON_PATH_88}/media/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped