services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    command: tunnel run
    restart: unless-stopped
    ports:
      - "20241:20241"
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - WEBUI_PORT=8080
      - PUID=0
      - PGID=0
      - TZ=${TZ}
      # - DOCKER_MODS=ghcr.io/gabe565/linuxserver-mod-vuetorrent
    volumes:
      - ${COMMON_PATH}:/data
      - ./config/qbittorrent:/config
      - ${COMMON_PATH}/qbittorrent/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
    volumes:
      - ./config/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"


  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
    volumes:
      - ${COMMON_PATH}:/data
      - ${COMMON_PATH}/media/tv:/tv
      - ./config/sonarr:/config
    ports:
      - 8989:8989
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
    volumes:
      - ${COMMON_PATH}:/data
      - ${COMMON_PATH}/media/movies:/movies
      - ./config/radarr:/config
    ports:
      - 7878:7878
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # readarr:
  #   image: lscr.io/linuxserver/readarr:develop
  #   container_name: readarr
  #   environment:
  #     - PUID=0
  #     - PGID=0
  #     - TZ=${TZ}
  #   volumes:
  #     - ${COMMON_PATH}:/data
  #     - ${COMMON_PATH}/media/books:/books
  #     - ./config/readarr:/config
  #     - ${COMMON_PATH}/qbittorrent/downloads:/downloads
  #     # - ${COMMON_PATH}/usenet/downloads:/usenet-downloads
  #     # - ${COMMON_PATH}/usenet/incomplete:/usenet-incomplete-downloads
  #   ports:
  #     - 8787:8787
  #   restart: unless-stopped

  # whisparr:
  #   container_name: whisparr
  #   image: ghcr.io/hotio/whisparr
  #   ports:
  #     - "6969:6969"
  #   environment:
  #     - PUID=0
  #     - PGID=0
  #     - UMASK=002
  #     - TZ={TZ}
  #   volumes:
  #     - ${COMMON_PATH}:/data
  #     - ${COMMON_PATH}/media/ram:/ram
  #     - ./config/whisparr:/config

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
    ports:
      - 8191:8191
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
    volumes:
      - ./config/sabnzbd/config:/config
      - ${COMMON_PATH}:/data
    ports:
      - 8081:8080
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=${TZ}
    volumes:
      - ./config/bazarr:/config
      - ${COMMON_PATH}:/data
      - ${COMMON_PATH}/media/movies:/movies
      - ${COMMON_PATH}/media/tv:/tv
    ports:
      - 6767:6767
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"